const beVsDoRecognitionItems = [
  {
    id: 'a1-u8-be-do-recognition-001',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'answer-about-home',
    topic: 'home',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: 'I ___ at home in the evening.',
    options: ['am', 'is', 'are', 'do', 'does'],
    correctAnswer: 'am',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'Qui non c’è un verbo normale come work o study. Serve be: I am at home.'
  },
  {
    id: 'a1-u8-be-do-recognition-002',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-home',
    topic: 'home',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ you at home now?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Are',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'Con you e be, la domanda è: Are you...?'
  },
  {
    id: 'a1-u8-be-do-recognition-003',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'answer-about-work',
    topic: 'work',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: 'We ___ busy on Monday mornings.',
    options: ['am', 'is', 'are', 'do', 'does'],
    correctAnswer: 'are',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'Busy è un aggettivo. Con we si usa are: We are busy.'
  },
  {
    id: 'a1-u8-be-do-recognition-004',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-study',
    topic: 'study',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ they students?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Are',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'Students è un nome. Con they si usa are: Are they students?'
  },
  {
    id: 'a1-u8-be-do-recognition-005',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'answer-about-language',
    topic: 'language',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: 'I ___ Italian.',
    options: ['am', 'is', 'are', 'do', 'does'],
    correctAnswer: 'am',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'Per dire nazionalità/identità si usa be: I am Italian.'
  },
  {
    id: 'a1-u8-be-do-recognition-006',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-language',
    topic: 'language',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ you English?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Are',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'Con you e be, la domanda è: Are you English?'
  },
  {
    id: 'a1-u8-be-do-recognition-007',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'answer-about-routines',
    topic: 'routine',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: 'We ___ ready.',
    options: ['am', 'is', 'are', 'do', 'does'],
    correctAnswer: 'are',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'Ready è un aggettivo. Con we si usa are: We are ready.'
  },
  {
    id: 'a1-u8-be-do-recognition-008',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'continue-basic-conversation',
    topic: 'free-time',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ you free after work?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Are',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'Free è un aggettivo. Con you si usa are: Are you free?'
  },

  {
    id: 'a1-u8-be-do-recognition-009',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'answer-about-home',
    topic: 'home',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: 'She ___ at home today.',
    options: ['am', 'is', 'are', 'do', 'does'],
    correctAnswer: 'is',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'Con she e be si usa is: She is at home.'
  },
  {
    id: 'a1-u8-be-do-recognition-010',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-work',
    topic: 'work',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ he a waiter?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Is',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'A waiter è un nome. Con he si usa is: Is he a waiter?'
  },
  {
    id: 'a1-u8-be-do-recognition-011',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'answer-about-study',
    topic: 'study',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: 'It ___ an easy lesson.',
    options: ['am', 'is', 'are', 'do', 'does'],
    correctAnswer: 'is',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'Con it e be si usa is: It is an easy lesson.'
  },
  {
    id: 'a1-u8-be-do-recognition-012',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-home',
    topic: 'home',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ your room small?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Is',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'Your room è singolare. Con be si usa is: Is your room small?'
  },
  {
    id: 'a1-u8-be-do-recognition-013',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'answer-about-work',
    topic: 'work',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: 'He ___ tired after work.',
    options: ['am', 'is', 'are', 'do', 'does'],
    correctAnswer: 'is',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'Tired è un aggettivo. Con he si usa is: He is tired.'
  },
  {
    id: 'a1-u8-be-do-recognition-014',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-language',
    topic: 'language',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ she Italian?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Is',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'Con she e be, la domanda è: Is she Italian?'
  },
  {
    id: 'a1-u8-be-do-recognition-015',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'answer-about-routines',
    topic: 'routine',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: 'The bus ___ always late in the morning.',
    options: ['am', 'is', 'are', 'do', 'does'],
    correctAnswer: 'is',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'The bus è singolare. Con be si usa is: The bus is late.'
  },
  {
    id: 'a1-u8-be-do-recognition-016',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'answer-about-needs',
    topic: 'basic-needs',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: 'The water ___ cold.',
    options: ['am', 'is', 'are', 'do', 'does'],
    correctAnswer: 'is',
    feedbackKeys: ['be-and-do-confusion'],
    visibleExplanation: 'Cold è un aggettivo. Con the water si usa is: The water is cold.'
  },

  {
    id: 'a1-u8-be-do-recognition-017',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-work',
    topic: 'work',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ you work on Saturdays?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Do',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement'],
    visibleExplanation: 'Work è un verbo normale. Con you si usa do: Do you work...?'
  },
  {
    id: 'a1-u8-be-do-recognition-018',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-study',
    topic: 'study',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ you study English every day?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Do',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement'],
    visibleExplanation: 'Study è un verbo normale. Con you si usa do: Do you study...?'
  },
  {
    id: 'a1-u8-be-do-recognition-019',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-home',
    topic: 'home',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ they live near the station?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Do',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement'],
    visibleExplanation: 'Live è un verbo normale. Con they si usa do: Do they live...?'
  },
  {
    id: 'a1-u8-be-do-recognition-020',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-routines',
    topic: 'routine',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ you get up early?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Do',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement'],
    visibleExplanation: 'Get up è un verbo normale. Con you si usa do: Do you get up...?'
  },
  {
    id: 'a1-u8-be-do-recognition-021',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-likes',
    topic: 'likes',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ you like coffee?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Do',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement'],
    visibleExplanation: 'Like è un verbo normale. Con you si usa do: Do you like...?'
  },
  {
    id: 'a1-u8-be-do-recognition-022',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-language',
    topic: 'language',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ they speak English at work?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Do',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement'],
    visibleExplanation: 'Speak è un verbo normale. Con they si usa do: Do they speak...?'
  },
  {
    id: 'a1-u8-be-do-recognition-023',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-needs',
    topic: 'basic-needs',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ you need help?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Do',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement'],
    visibleExplanation: 'Need è un verbo normale. Con you si usa do: Do you need...?'
  },
  {
    id: 'a1-u8-be-do-recognition-024',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-routines',
    topic: 'food-drink',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ we have lunch at one?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Do',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement'],
    visibleExplanation: 'Have è un verbo normale. Con we si usa do: Do we have lunch...?'
  },

  {
    id: 'a1-u8-be-do-recognition-025',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-work',
    topic: 'work',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ he work in a hotel?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Does',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement', 'does-followed-by-base-verb'],
    visibleExplanation: 'Work è un verbo normale. Con he si usa does: Does he work...?'
  },
  {
    id: 'a1-u8-be-do-recognition-026',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-study',
    topic: 'study',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ she study English?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Does',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement', 'does-followed-by-base-verb'],
    visibleExplanation: 'Study è un verbo normale. Con she si usa does: Does she study...?'
  },
  {
    id: 'a1-u8-be-do-recognition-027',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-home',
    topic: 'home',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ he live near you?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Does',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement', 'does-followed-by-base-verb'],
    visibleExplanation: 'Live è un verbo normale. Con he si usa does: Does he live...?'
  },
  {
    id: 'a1-u8-be-do-recognition-028',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-routines',
    topic: 'routine',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ she start work at nine?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Does',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement', 'does-followed-by-base-verb'],
    visibleExplanation: 'Start è un verbo normale. Con she si usa does: Does she start...?'
  },
  {
    id: 'a1-u8-be-do-recognition-029',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-likes',
    topic: 'likes',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ he like tea?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Does',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement', 'does-followed-by-base-verb'],
    visibleExplanation: 'Like è un verbo normale. Con he si usa does: Does he like...?'
  },
  {
    id: 'a1-u8-be-do-recognition-030',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-language',
    topic: 'language',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ she speak Italian?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Does',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement', 'does-followed-by-base-verb'],
    visibleExplanation: 'Speak è un verbo normale. Con she si usa does: Does she speak...?'
  },
  {
    id: 'a1-u8-be-do-recognition-031',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-needs',
    topic: 'basic-needs',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ he need water?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Does',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement', 'does-followed-by-base-verb'],
    visibleExplanation: 'Need è un verbo normale. Con he si usa does: Does he need...?'
  },
  {
    id: 'a1-u8-be-do-recognition-032',
    unitId: 'a1-present-simple-normal-verbs',
    grammarArea: 'present-simple',
    form: 'be-vs-do-recognition',
    languageFunction: 'ask-about-routines',
    topic: 'free-time',
    productionMode: 'recognition',
    prompt: 'Scegli la parola corretta.',
    sentence: '___ she play tennis after work?',
    options: ['Am', 'Is', 'Are', 'Do', 'Does'],
    correctAnswer: 'Does',
    feedbackKeys: ['normal-verb-question-needs-do', 'be-and-do-confusion', 'do-does-subject-agreement', 'does-followed-by-base-verb'],
    visibleExplanation: 'Play è un verbo normale. Con she si usa does: Does she play...?'
  }
];

export const beVsDoRecognitionPool = beVsDoRecognitionItems.map((item) => ({
  ...item,
  type: 'choice',
  correctIndex: item.options.indexOf(item.correctAnswer),
}));
