export const EDUCATIONAL_CONTENT_TEMPLATE_ID = 'educational-content-block-v1';
export const EDUCATIONAL_CONTENT_TEMPLATE_VERSION = 1;

export const educationalContentBlockAuthoringGuide = {
  template_id: EDUCATIONAL_CONTENT_TEMPLATE_ID,
  template_version: EDUCATIONAL_CONTENT_TEMPLATE_VERSION,
  purpose: 'Generate a structured teaching content_block for Sblocco Inglese. The downloaded JSON must be sufficient for an AI in a new chat to produce an import-ready block without access to the codebase.',
  workflow: [
    'Read this entire _template object before generating content.',
    'Use the pedagogical contract that matches question.content.variant.',
    'Return one complete JSON object with the same top-level structure.',
    'Keep _template in the returned file so the template remains self-contained when downloaded or reused.',
  ],
  generation_contract: {
    output: 'valid_json_only',
    markdown_fences: false,
    comments: false,
    preserve_top_level_metadata: true,
    do_not_rename_keys: true,
    do_not_add_unsupported_section_types: true,
    invariant_fields: [
      'schema_version',
      'entity_type',
      '_template',
      'question.type',
      'question.content.educational_schema_version',
      'question.content.template_id',
    ],
    editable_fields: [
      'question.client_key',
      'question.title',
      'question.prompt',
      'question.instructions',
      'question.instruction_language',
      'question.level',
      'question.topic',
      'question.subtopic',
      'question.primary_skill',
      'question.learning_objective',
      'question.difficulty',
      'question.content.variant',
      'question.content.body',
      'question.content.intro',
      'question.content.sections',
      'question.tags',
    ],
  },
  supported_variants: [
    'general',
    'grammar',
    'vocabulary',
    'functional_language',
    'dialogue',
    'pronunciation',
    'strategy',
    'recap',
    'instructions',
  ],
  supported_section_types: [
    'rule',
    'example',
    'mistake',
    'comparison',
    'tip',
    'pattern',
    'dialogue',
    'vocabulary',
    'recap',
  ],
  global_pedagogical_rules: [
    'Do not write one long explanatory paragraph when the idea can be split into pedagogically meaningful sections.',
    'Use Italian for explanations unless the requested lesson explicitly requires English-only instructions. Keep English examples in English.',
    'Make the target language natural, contemporary and usable in real situations; do not write examples only to display a grammar form.',
    'Prioritise difficulties that commonly affect Italian learners when they are relevant to the target point.',
    'Teach one clear idea per rule section. A rule should normally be followed by one or more examples.',
    'Use contrast when it prevents a likely error. Do not invent an error merely to fill a mistake section.',
    'Keep metalinguistic terminology proportionate to the CEFR level. A0-A2 explanations should favour plain language over unnecessary grammar jargon.',
    'Do not duplicate the same explanation across intro, body and recap.',
    'The legacy body is a compact fallback summary, not a copy of every structured section.',
    'Do not encode presentation in content: no CSS classes, colours, layout instructions, HTML, check marks, crosses or decorative emoji.',
    'Use highlight metadata for target words or chunks instead of markdown bold inside examples.',
  ],
  length_rules: {
    intro_max_words: 45,
    section_body_max_words: 55,
    tip_max_words: 40,
    recap_point_max_words: 24,
    recommended_rule_count: '2-5',
    recommended_examples_per_rule: '1-3',
  },
  section_contracts: {
    rule: {
      purpose: 'Explain one form, use or constraint.',
      required: ['type', 'body or explanation'],
      recommended: ['title', 'examples'],
      example_shape: { text: 'an expensive phone', highlight: ['expensive'], translation: '' },
    },
    example: {
      purpose: 'Show target language without adding a new rule.',
      required: ['type', 'examples'],
      example_shape: { text: 'You look tired.', highlight: ['tired'], translation: '' },
    },
    mistake: {
      purpose: 'Contrast a plausible learner error with the correct form.',
      required: ['type', 'correct and/or incorrect'],
      correct_incorrect_shape: {
        correct: { text: 'blue eyes', highlight: ['blue'] },
        incorrect: { text: 'blues eyes', highlight: ['blues'] },
      },
    },
    comparison: {
      purpose: 'Contrast two forms, meanings, registers or contexts.',
      required: ['type', 'correct and/or incorrect'],
      note: 'The renderer labels the two sides. Do not insert visual status symbols in text.',
    },
    tip: {
      purpose: 'Give a short memory aid or usage strategy.',
      required: ['type', 'body or explanation'],
    },
    pattern: {
      purpose: 'Expose a reusable language pattern.',
      required: ['type', 'pattern and/or body'],
      example: 'adjective + noun',
    },
    dialogue: {
      purpose: 'Place language in a natural exchange.',
      required: ['type', 'turns'],
      minimum_turns: 2,
      turn_shape: { speaker: 'Customer', text: 'Could I try this one?', highlight: ['Could I'] },
    },
    vocabulary: {
      purpose: 'Teach words, chunks or collocations in context.',
      required: ['type', 'items'],
      item_shape: { term: 'make a decision', meaning: 'decidere', example: 'We need to make a decision today.', highlight: ['make a decision'] },
    },
    recap: {
      purpose: 'Compress the essential takeaways before practice or assessment.',
      required: ['type', 'body and/or points'],
    },
  },
  variant_contracts: {
    grammar: [
      'Cover both form and use when both matter.',
      'Use rule + example as the default teaching rhythm.',
      'Include mistake/comparison only for a real high-probability confusion.',
      'For lower levels, prefer concrete examples before abstract labels.',
    ],
    vocabulary: [
      'Do not generate isolated word lists when collocations or chunks are more useful.',
      'Give contextual examples and distinguish close meanings only when relevant.',
      'Prefer high-utility vocabulary appropriate to the requested CEFR level.',
    ],
    functional_language: [
      'Start from a real communicative situation.',
      'Teach multiple natural options when register or tone can vary.',
      'Use dialogue sections when an exchange clarifies how the expression functions.',
    ],
    dialogue: [
      'Make turns respond to each other naturally.',
      'Do not write a dialogue whose only purpose is to mechanically repeat the target grammar.',
      'Keep speaker roles and register internally consistent.',
    ],
    pronunciation: [
      'Explain only features learners can act on.',
      'Use examples to show stress, sound contrast or connected speech without inventing unsupported phonetic notation.',
    ],
    strategy: [
      'Give an actionable listening, speaking, reading or writing strategy and show when to use it.',
      'Avoid generic motivational advice.',
    ],
    recap: [
      'Do not introduce new rules.',
      'Prioritise the few points the learner must retain for the next activity.',
    ],
    instructions: [
      'Explain the task, success criteria and any constraints without teaching unrelated content.',
      'Keep instructions operational and concise.',
    ],
    general: [
      'Choose only the section types that genuinely improve comprehension.',
    ],
  },
  highlight_rules: [
    'Every highlight entry must be an exact substring of the associated text.',
    'Highlight only the target form or chunk, not the whole sentence unless the whole sentence is the target.',
    'Do not use markdown bold as a substitute for highlight metadata in examples.',
  ],
  invalid_patterns: [
    'A single 150-word body with no structured sections.',
    'HTML, CSS classes, inline styles or colour names inside content.',
    'Unsupported section.type values invented for one lesson.',
    'Correct/incorrect strings prefixed with check marks or crosses.',
    'Examples that are unnatural but grammatically convenient.',
    'Repeating the same rule in intro, rule, tip and recap.',
  ],
};

export const educationalContentBlockTemplate = {
  schema_version: 2,
  entity_type: 'question',
  _template: educationalContentBlockAuthoringGuide,
  question: {
    client_key: 'question_educational_content_block',
    type: 'content_block',
    title: 'Adjectives: forma e posizione',
    prompt: 'Prima di iniziare',
    instructions: 'Leggi la spiegazione e osserva gli esempi prima di continuare.',
    instruction_language: 'it',
    level: 'A1',
    topic: 'adjectives',
    subtopic: 'position_and_form',
    primary_skill: 'grammar',
    learning_objective: 'Recognise where English adjectives go and use the same adjective form with singular and plural nouns.',
    difficulty: 'standard',
    content: {
      educational_schema_version: 1,
      template_id: EDUCATIONAL_CONTENT_TEMPLATE_ID,
      variant: 'grammar',
      body: 'Gli aggettivi descrivono persone e cose. In inglese vengono normalmente prima del nome oppure dopo verbi come be, look e feel. Non cambiano forma al plurale.',
      intro: 'Gli aggettivi descrivono persone e cose. Guarda dove si trovano nella frase e nota una differenza importante rispetto all’italiano.',
      sections: [
        {
          key: 'rule_before_noun',
          type: 'rule',
          title: 'Prima del nome',
          body: 'Quando un aggettivo descrive direttamente un nome, viene normalmente prima del nome.',
          examples: [
            { text: 'an expensive phone', highlight: ['expensive'] },
            { text: 'a small apartment', highlight: ['small'] },
          ],
        },
        {
          key: 'rule_after_linking_verb',
          type: 'rule',
          title: 'Dopo be, look, feel…',
          body: 'L’aggettivo può anche venire dopo be e altri verbi che descrivono stato o impressione, come look, feel, sound, smell e taste.',
          examples: [
            { text: 'The phone is expensive.', highlight: ['expensive'] },
            { text: 'You look tired.', highlight: ['tired'] },
          ],
        },
        {
          key: 'pattern_adjective_noun',
          type: 'pattern',
          title: 'Lo schema utile',
          body: 'Quando descrivi un nome direttamente, pensa a questo ordine.',
          pattern: 'adjective + noun',
          examples: [
            { text: 'blue eyes', highlight: ['blue'] },
          ],
        },
        {
          key: 'mistake_no_plural',
          type: 'mistake',
          title: 'L’aggettivo non prende il plurale',
          body: 'In inglese l’aggettivo resta uguale anche quando il nome è plurale.',
          correct: { text: 'blue eyes', highlight: ['blue'] },
          incorrect: { text: 'blues eyes', highlight: ['blues'] },
        },
        {
          key: 'recap',
          type: 'recap',
          title: 'Prima di esercitarti',
          points: [
            'Adjective + noun: a small room.',
            'Dopo be/look/feel: The room is small.',
            'L’aggettivo non cambia al plurale.',
          ],
        },
      ],
    },
    grading: { mode: 'automatic', weight: 1, nearly_correct_multiplier: 0.5 },
    feedback: {},
    diagnostics: { tested_codes: [], fallback_error_code: null },
    tags: ['content_block', 'educational', 'grammar', 'structured'],
    foundation_links: [],
  },
};
