export const adminButton = {
  primary: 'focus-ring inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-ink px-5 py-2.5 text-sm font-black text-white transition hover:bg-moss disabled:cursor-not-allowed disabled:bg-ink/20 disabled:text-ink/65 disabled:ring-1 disabled:ring-inset disabled:ring-ink/15 dark:bg-emerald-400 dark:text-[#07120f] dark:hover:bg-emerald-300 dark:disabled:bg-white/10 dark:disabled:text-white/65 dark:disabled:ring-white/15',
  secondary: 'focus-ring inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-ink/15 bg-white px-5 py-2.5 text-sm font-black text-ink transition hover:border-moss/30 hover:bg-linen disabled:cursor-not-allowed disabled:border-ink/15 disabled:bg-ink/5 disabled:text-ink/65 dark:border-white/20 dark:bg-white/10 dark:text-white dark:hover:border-emerald-300/35 dark:hover:bg-white/15 dark:disabled:border-white/15 dark:disabled:bg-white/[0.07] dark:disabled:text-white/65',
  positive: 'focus-ring inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-moss/35 bg-mint/60 px-5 py-2.5 text-sm font-black text-ink transition hover:bg-mint disabled:cursor-not-allowed disabled:border-ink/15 disabled:bg-ink/5 disabled:text-ink/65 dark:border-emerald-300/45 dark:bg-emerald-400/15 dark:text-emerald-100 dark:hover:bg-emerald-400/25 dark:disabled:border-white/15 dark:disabled:bg-white/[0.07] dark:disabled:text-white/65',
  destructive: 'focus-ring inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-red-700 px-5 py-2.5 text-sm font-black text-white transition hover:bg-red-800 disabled:cursor-not-allowed disabled:bg-red-700/25 disabled:text-ink/60 dark:bg-red-500 dark:text-white dark:hover:bg-red-400 dark:disabled:bg-red-500/15 dark:disabled:text-white/65',
  danger: 'focus-ring inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-red-700 px-5 py-2.5 text-sm font-black text-white transition hover:bg-red-800 disabled:cursor-not-allowed disabled:bg-red-700/25 disabled:text-ink/60 dark:bg-red-500 dark:text-white dark:hover:bg-red-400 dark:disabled:bg-red-500/15 dark:disabled:text-white/65',
  ghost: 'focus-ring inline-flex min-h-10 items-center justify-center gap-2 rounded-xl px-3 py-2 text-sm font-black text-ink/70 transition hover:bg-linen hover:text-ink disabled:cursor-not-allowed disabled:text-ink/60 dark:text-white/70 dark:hover:bg-white/10 dark:hover:text-white dark:disabled:text-white/60',
};

export const adminSurface = {
  panel: 'rounded-2xl border border-ink/10 bg-white shadow-sm dark:border-white/10 dark:bg-white/[0.06]',
  muted: 'rounded-xl border border-ink/10 bg-linen/35 dark:border-white/10 dark:bg-white/[0.04]',
};
