-- Allow learner-facing Exercise Builder RPCs to persist server-side automatic
-- grading while keeping every teacher-authored review field admin-only.
--
-- The existing UPDATE trigger runs with the learner's auth context even when a
-- SECURITY DEFINER grading RPC performs the update. `automatic_grading_result`
-- is generated by trusted database functions, not entered by a teacher, so
-- treating it as a teacher-only field blocks section completion for learners.
-- Direct table updates remain protected by RLS; learners can only reach these
-- rows through the granted SECURITY DEFINER RPCs.

create or replace function public.protect_exercise_builder_teacher_review_fields()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if not public.is_admin() then
    if tg_table_name = 'exercise_builder_attempt_questions' then
      if new.teacher_status_override is distinct from old.teacher_status_override
        or new.teacher_points_override is distinct from old.teacher_points_override
        or new.teacher_comment is distinct from old.teacher_comment
        or new.reviewed_by is distinct from old.reviewed_by
        or new.reviewed_at is distinct from old.reviewed_at then
        raise exception 'Teacher review fields are admin-only.';
      end if;
    elsif tg_table_name = 'exercise_builder_attempts' then
      if new.teacher_note is distinct from old.teacher_note
        or new.review_status is distinct from old.review_status
        or new.reviewed_by is distinct from old.reviewed_by
        or new.reviewed_at is distinct from old.reviewed_at then
        raise exception 'Teacher review fields are admin-only.';
      end if;
    end if;
  end if;

  return new;
end;
$$;

comment on function public.protect_exercise_builder_teacher_review_fields() is
  'Blocks learner changes to teacher-authored review fields while allowing trusted grading RPCs to persist automatic_grading_result.';

notify pgrst, 'reload schema';
